-  name: Configura el frontend
   hosts: frontend
   become: true
   tasks:
     -  name: Instala .net
        dnf:
          name: dotnet-sdk-6.0
          state: present
     -  name: Instala Node.js
        dnf:
          name: nodejs
          state: present
        
-  name: Configura Backend
   hosts: backend
   become: true
   tasks:
     -  name: Importa la clave GPG de PostgreSQL
        ansible.builtin.rpm_key:
          state: present
          key: https://download.postgresql.org/pub/repos/yum/keys/RPM-GPG-KEY-PGDG
     -  name: Instala postgres repos
        dnf:
          name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm
          state: present
     -  name: Instala postgres
        dnf:
          name: postgresql18-server
          state: present
          disable_gpg_check: true
     -  name: Inicializa la base de datos de PostgreSQL
        command: /usr/pgsql-18/bin/postgresql-18-setup initdb 
        